### PR TITLE
Update rustfft dependency to version 6

### PR DESCRIPTION
**Pull request by mpizenberg**
This PR intends to update rust_dct to use the latest version (6) of rust_fft.

This is the minimum viable PR that is compiling and passing the tests for me. But since this is a breaking change there are few other changes that you might want to include here? The two I can imagine are:

1. Update the `rand` dev dependency from 0.4 to 0.8
2. Adding an equivalent to the `process_outofplace_with_scratch`

(1) isn't that important I guess.
(2) could also be done later as a minor release if managed to be done as only adding new functions, otherwise might need another breaking change if changing some of the functions names.

### CODE REVIEW

**Comment by mpizenberg** [comment]
Actually, I didn't realize but some tests are not passing when doing `cargo test` while they pass when doing `cargo test --release`. I have no idea why that is. Here is the end of the normal (not `--release`) output:
```
...

failures:
    test_dct2_accuracy
    test_dct3_accuracy
    test_dst2_accuracy
    test_dst3_accuracy

test result: FAILED. 14 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s
```

**Comment by mpizenberg** [comment]
Ooooh my bad, it was written clearly why the test failed:
```
thread 'test_dst3_accuracy' panicked at 'attempt to subtract with overflow', /home/matthieu/git/ejmahler/rust_dct/src/algorithm/type2and3_convert_to_fft.rs:215:23
```
There seems to be some overflowing substraction in the code executed by those tests. I don't know you want to do about that? This seems to also be the case when I run the tests with the old `rustfft` version (version 5). So it's unrelated to this release, but still maybe something you want to address when upgrading?

**Comment by ejmahler** [comment]
Very good to know. I'll look into fixing the test and adding that to this PR before submitting

**Comment by ejmahler** [comment]
Thanks for your help.

**Pull request merged**
